<template>
  <div class="loadingio-spinner-spinner-pfdodo1yurm">
    <div class="ldio-wju9re0qapr">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>

<script lang="ts">
    import Vue from 'vue'

    export default Vue.extend({
        
    })
</script>

<style scoped>
@keyframes ldio-wju9re0qapr {
  0% { opacity: 1 }
  100% { opacity: 0 }
}
.ldio-wju9re0qapr div {
  left: 141px;
  top: 72px;
  position: absolute;
  animation: ldio-wju9re0qapr linear 1s infinite;
  background: #f7fe71;
  width: 18px;
  height: 36px;
  border-radius: 9px / 18px;
  transform-origin: 9px 78px;
}.ldio-wju9re0qapr div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9166666666666666s;
  background: #fe718d;
}.ldio-wju9re0qapr div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.8333333333333334s;
  background: #f47e60;
}.ldio-wju9re0qapr div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.75s;
  background: #f8b26a;
}.ldio-wju9re0qapr div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.6666666666666666s;
  background: #abbd81;
}.ldio-wju9re0qapr div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.5833333333333334s;
  background: #849b87;
}.ldio-wju9re0qapr div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.5s;
  background: #6492ac;
}.ldio-wju9re0qapr div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.4166666666666667s;
  background: #637cb5;
}.ldio-wju9re0qapr div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3333333333333333s;
  background: #6a63b6;
}.ldio-wju9re0qapr div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.25s;
  background: #fe718d;
}.ldio-wju9re0qapr div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.16666666666666666s;
  background: #f47e60;
}.ldio-wju9re0qapr div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.08333333333333333s;
  background: #f8b26a;
}.ldio-wju9re0qapr div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #abbd81;
}
.loadingio-spinner-spinner-pfdodo1yurm {
  width: 300px;
  height: 300px;
  display: inline-block;
  overflow: hidden;
  background: rgba(NaN, NaN, NaN, 0);
}
.ldio-wju9re0qapr {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-wju9re0qapr div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>